services:
  backend:
    image: backend
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - "5432:5432"
  
  frontend:
    image: frontend